config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"
  devise_for :users
  resources :users
  resources :fukus do
    resources :likes, only:[:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fuku.rb
class Fuku < ApplicationRecord
    attachment :image
    belongs_to :user
    has_many :likes

    validates :title, presence: true
    validates :body, presence: true
    validates :image, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :fuku
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :fukus
  has_many :likes
  
  validates :name, presence: true
  validates :email, presence: true
  validates :profile_image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

def configure_permitted_parameters
devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile_image])
end


end

app/controllers/fukus_controller.rb
class FukusController < ApplicationController

  before_action :authenticate_user!, except: [:index]
  def index
    @fukus=Fuku.all
  end

  def show
    @fuku=Fuku.find_by(id:params[:id])
  end

  def new
    @fuku=Fuku.new
  end

  def create
    @fuku=Fuku.new(fuku_params)
    @fuku.user_id=current_user.id
    if @fuku.save
      flash[:notice] ="記事を投稿しました"
      redirect_to fukus_path
    else
      render action: :new
    end

  end

   def edit
    @fuku=Fuku.find_by(id:params[:id])
    if @fuku.user_id !=current_user.id
      redirect_to fukus_path, alert: "不正なアクセスです。"
    end
   end

  def update
    @fuku=Fuku.find_by(id:params[:id])
    if@fuku.update(fuku_params)
      flash[:notice]="レシピを編集しました"
      redirect_to fukus_path
    end
  end

  def destroy
    @fuku=Fuku.find_by(id:params[:id])
    @fuku.destroy
    redirect_to(fukus_path)
  end



  private
  def fuku_params
      params.require(:fuku).permit(:title, :body, :image)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        @like=Like.new(user_id:current_user.id, fuku_id:params[:fuku_id])
        @like.save
        redirect_back(fallback_location: root_path)
    end

    def destroy
        @like=Like.find_by(user_id:current_user.id, fuku_id:params[:fuku_id])
        @like.destroy
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @users=User.all
  end

  def show
    @user=User.find_by(id:params[:id])
    @fukus=Fuku.where(user_id:@user.id)
    @likes=Like.where(user_id:@user.id)
  end
  

  def edit
    @user=User.find_by(id:params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       bypass_sign_in(@user)
       redirect_to user_path(@user)
       flash[:notice] = 'プロフィールを編集しました'
    else
      render action: :edit
    end
  end


private
def user_params
    params.require(:user).permit(:name, :email, :profile_image, :password)
end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fukus_helper.rb
module FukusHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fukus/edit.html.erb
<div class="form">
　<h2 class="title">編集画面</h2>
        <%= form_for @fuku do |f| %>
          <div class="field">
            <%= f.label :title, "タイトル", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "概要", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>

           <%= f.submit '編集', class: "submit" %>
        <% end %>
  </div>

app/views/fukus/index.html.erb
<h2 class="is-size-3">投稿一覧</h2>
  <div class="columns is-multiline is-centered">
   <% @fukus.each do |fuku|%>
    <div class="column is-4 has-text-centered">
      <div class="card has-text-centered">
       <div class="card-content">
           <%= link_to(fuku_path(fuku)) do %>
        　 <%=attachment_image_tag fuku,:image,class:"thumbnail150" %>
           <% end %>
       </div>
      </div>
    </div>
    <%end%>
    </div>

app/views/fukus/new.html.erb
<div class="form">
<h2 class="title">新規投稿</h2>

<%= form_for @fuku do |f| %>
<% if @fuku.errors.any? %>
  <div class="notification is-danger">
    <h3>入力した内容にエラーが<%= @fuku.errors.count %>件あります</h3>
    <ul>
      <% @fuku.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

          <div class="field">
            <%= f.label :title, "タイトル", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "概要", class: "label" %>
            <%= f.text_field :body, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>
          
          <%= f.submit '投稿', class: "submit" %>
<% end %>
</div>

app/views/fukus/show.html.erb
<h2 class="is-size-3">服の詳細</h2>
  <div class="columns is-multiline is-centered">
    <div class="column is-4 has-text-centered">
      <div class="card">
       <div class="card-content">
          <p><%= attachment_image_tag @fuku, :image , class:"thumbnail150"%></p>
          <p><%=@fuku.user.name%></p>
　　　　　　<p><%=@fuku.title%></p>
　　　　　　<p><%=@fuku.body%></p>　　
　　　　　　<% if Like.find_by(user_id:current_user.id, fuku_id:@fuku.id)%>
　　　　　　<p><%= link_to 'いいね済み', fuku_like_path(@fuku), method: :delete,class:"like"%></p>
 　　　　　 <%else%> 
          <p><%= link_to 'いいね', fuku_likes_path(@fuku), method: :post,class:"like"%></p>
　　　　　　<%end%>
         <p><%= link_to('編集', edit_fuku_path) %></p>
         <p><%= link_to '削除', fuku_path(@fuku), method: :delete %></p>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<section class="section">
  <article class="media">
    <div class="media-content">
      <div class="content has-text-centered">
        <p>
          <strong class="is-size-1" style="font-family: cursive;">FusuShare</strong>
        </p>
        <p>友人同士で服をシェアしよう</p>

      </div>
      <div class="columns is-centered">
        <div class="column is-5">
          <br>
          <%= link_to "ログイン", new_user_session_path, class: "button is-fullwidth" %>
          <br>
          <%= link_to "新規登録", new_user_registration_path, class: "button  is-fullwidth" %>
        </div>
      </div>
    </div>
  </article>
  <br>
  <div class="columns is-centered">
    <div class="column">
      <figure>
        <div class="main-image"></div>
      </figure>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FukuShare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
　  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  </head>

  <body>
   <header> 
    <% if flash[:notice] %>
     <div class="notification">
      <p class="notice"><%= notice %></p>
     </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification">
       <p class="alert"><%= alert %></p>
      </div>
    <% end %>
  
   <nav class="navbar has-background-black">
     <div class="navbar-brand">
      <%= link_to root_path, class: "navbar-item has-text-white" do %>
       <i class="fas fa-tshirt fa-2x"></i><h1 class="title has-text-white" style="font-family: cursive;">FukuShare</h1>
      <% end %>
        
      <%if user_signed_in?%> 
        <p class="navbar-item has-text-white">ようこそ<%=current_user.name%>さん!</p>
      <%end%> 

      <a role="button" class="navbar-burger burger has-background-black" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
     </div>

     <%if user_signed_in?%>   
      <div id="navbarBasicExample" class="navbar-menu">
       <div class="navbar-end">
        <div class="navbar-item">
          <%= link_to("マイページ", user_path(current_user),class:"has-text-white") %>
        </div>
        <div class="navbar-item">
         <%= link_to("ユーザー一覧", users_path, class:"has-text-white") %> 
        </div>
        <div class="navbar-item">
          <%= link_to("投稿一覧", fukus_path,class:"has-text-white") %>
        </div>
        <div class="navbar-item">
         <%= link_to("新規投稿", new_fuku_path,class:"has-text-white") %>
        </div>
        <div class="navbar-item">
          <%= link_to("ログアウト", destroy_user_session_path, method: :delete,class:"has-text-white") %>
        </div>
       </div>
      </div>

    <%else%>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-end">
        <div class="navbar-item">
          <%= link_to("ユーザー一覧", users_path, class:"has-text-white") %> 
        </div>
        <div class="navbar-item">
          <%= link_to("投稿一覧", fukus_path,class:"has-text-white") %>
        </div>
        <div class="navbar-item">
          <%= link_to("新規登録", new_user_registration_path,class:"has-text-white") %>
        </div>
        <div class="navbar-item">
          <%= link_to("ログイン", new_user_session_path,class:"has-text-white") %>
        </div>
      </div>
    </div>

    <%end%>
  </nav>


  <script type="text/javascript">
  document.querySelector('.navbar-burger').addEventListener("click", toggleNav);
  function toggleNav() {
        var nav = document.querySelector('.navbar-menu');
        if(nav.className == "navbar-menu") {
            nav.className = "navbar-menu is-active has-background-black";
        } else {
            nav.className = "navbar-menu";
        }
  }
   </script>


</header>
<%= yield %>

 
  </body>
</html>

app/views/users/edit.html.erb
<div class="form">
　<h2 class="title">編集画面</h2>
<%=form_for @user do |f| %>
<% if @user.errors.any? %>
  <div class="notification is-danger">
    <h3>入力した内容にエラーが<%= @user.errors.count %>件あります</h3>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%=f.label :名前 %>
<%=f.text_field :name %>

<%=f.label :メールアドレス %>
<%=f.text_field :email %>

<%= f.label :写真 %>
<%= f.attachment_field :profile_image %>  
  
<%=f.label :password %>
<%=f.text_field :password %>


 <%= f.submit '編集', class: "submit" %>

<%end%>
</div>

app/views/users/index.html.erb
<h2 class="is-size-3">ユーザー一覧</h2>
  <div class="columns is-multiline is-centered">
   <% @users.each do |user|%>
    <div class="column is-4 has-text-centered">
      <div class="card">
       <div class="card-content">
           <%= link_to(user_path(user)) do %>
        　 <%=attachment_image_tag user,:profile_image,class:"thumbnail150" %>
           <% end %>
       </div>
      </div>
    </div>
    <%end%>
    </div>

    

app/views/users/show.html.erb
<div class="columns is-centered">
  <div class="column is-4 has-text-centered">
   
      <%=attachment_image_tag @user,:profile_image, class:"thumbnail150"%>
      <p><%=@user.name%></p>
      <% if @user.id == current_user.id %>
      <p><%=@user.email%></p>
      <%= link_to '編集', edit_user_path(@user),class: "link_edit"%>
      <%end%>
  </div>
</div>

<h2 class="is-size-3">シェアした服</h2>
  <div class="columns is-multiline is-centered">
   <% @fukus.each do |fuku| %>
    <div class="column is-4 has-text-centered">
      <div class="card">
       <div class="card-content">
          <%= link_to(fuku_path(fuku)) do %>
          <%=attachment_image_tag fuku,:image,class:"thumbnail150" %>
          <% end %>
       </div>
      </div>
    </div>
   <% end %>
  </div>


  <h2 class="is-size-3">いいねした服</h2>
  <div class="columns is-multiline is-centered">
   <%@likes.each do |like|%>
    <div class="column is-4 has-text-centered">
      <div class="card">
       <div class="card-content">
         <% fuku=Fuku.find_by(id:like.fuku_id)%>
         <%= link_to(fuku_path(fuku)) do %>
          <%=attachment_image_tag fuku,:image,class:"thumbnail150" %>
          <% end %>
       </div>
      </div>
    </div>
   <% end %>
  </div>




 


 